[package]
name = "sdcore"
version = "0.1.0"
description = "Virtual distributed filesystem engine that powers Spacedrive."
authors = ["Spacedrive Technology Inc."]
license = "GNU GENERAL PUBLIC LICENSE"
repository = "https://github.com/spacedriveapp/spacedrive"
edition = "2021"

[features]
p2p = [] # This feature controlls whether the Spacedrive Core contains the Peer to Peer syncing engine (It isn't required for the hosted core so we can disable it).

[dependencies]
hostname = "0.3.1"

# Universal Dependencies
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
serde_json = "1.0"
futures = "0.3"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
int-enum = "0.4.0"

# Project dependencies
ts-rs = { version = "6.1", features = ["chrono-impl"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.5.0" }
walkdir = "^2.3.2"
lazy_static = "1.4.0"
uuid = "0.8"
sysinfo = "0.23.9"
thiserror = "1.0.30"
core-derive = { path = "./derive" }

tokio = { version = "1.17.0", features = ["sync", "rt"] }
include_dir = {version = "0.7.2", features = ["glob"]}
async-trait = "0.1.52"
image = "0.24.1"
webp = "0.2.2"
ffmpeg-next = "5.0.3"
fs_extra = "1.2.0"